name: Cleanup Branch After Merge

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.head.ref != 'main' && 
      github.event.pull_request.head.ref != 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: delete branch after merge
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
